### ISSUE TITLE
Libvirt built with mariner specs does not support qemu and lacks binaries

### ISSUE THREAD

**Issue by aostapenko** [microsoft/CBL-Mariner#1836] opened 2022-01-04 19:41 UTC
Libvirt lacks runtime binaries:

* libvirtd.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirtd.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-01-04 19:38:04 UTC; 1min 17s ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 654 (libvirtd)
    Tasks: 16 (limit: 32768)
   Memory: 2.8M
   CGroup: /system.slice/libvirtd.service
           `-654 /usr/sbin/libvirtd --timeout 120

Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 systemd[1]: Starting Virtualization daemon...
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 systemd[1]: Started Virtualization daemon.
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: libvirt version: 6.1.0
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: hostname: cbl-mariner-9MLCouLpY9t3
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: Cannot check dnsmasq binary dnsmasq: No such file or directory
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: direct firewall backend requested, but /sbin/ebtables is not available: No such file or directory
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: internal error: Failed to initialize a valid firewall backend
Jan 04 19:38:04 cbl-mariner-9MLCouLpY9t3 libvirtd[654]: internal error: Failed to find path for dmidecode binary

Libvirt lacks qemu support:
user@cbl-mariner-9MLCouLpY9t3 [ ~ ]$ sudo virsh capabilities
<capabilities>

  <host>
    <uuid>a4c53cef-7bcf-4be9-8fe6-7bc30b20204b</uuid>
    <cpu>
      <arch>x86_64</arch>
      <pages unit='KiB' size='4'/>
      <pages unit='KiB' size='2048'/>
      <pages unit='KiB' size='1048576'/>
    </cpu>
    <power_management/>
    <iommu support='no'/>
    <topology>
      <cells num='1'>
        <cell id='0'>
          <memory unit='KiB'>3897928</memory>
          <cpus num='4'>
            <cpu id='0' socket_id='0' die_id='0' core_id='0' siblings='0'/>
            <cpu id='1' socket_id='1' die_id='0' core_id='0' siblings='1'/>
            <cpu id='2' socket_id='2' die_id='0' core_id='0' siblings='2'/>
            <cpu id='3' socket_id='3' die_id='0' core_id='0' siblings='3'/>
          </cpus>
        </cell>
      </cells>
    </topology>
    <cache>
      <bank id='0' level='3' type='both' size='16' unit='MiB' cpus='0'/>
      <bank id='1' level='3' type='both' size='16' unit='MiB' cpus='1'/>
      <bank id='2' level='3' type='both' size='16' unit='MiB' cpus='2'/>
      <bank id='3' level='3' type='both' size='16' unit='MiB' cpus='3'/>
    </cache>
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
  </host>

  <guest>
    <os_type>exe</os_type>
    <arch name='x86_64'>
      <wordsize>64</wordsize>
      <emulator>/usr/libexec/libvirt_lxc</emulator>
      <domain type='lxc'/>
    </arch>
  </guest>

  <guest>
    <os_type>exe</os_type>
    <arch name='i686'>
      <wordsize>32</wordsize>
      <emulator>/usr/libexec/libvirt_lxc</emulator>
      <domain type='lxc'/>
    </arch>
  </guest>

</capabilities>

**Comment by PawelWMS** [comment] 2022-01-04 20:39
Hey, Andrii,

Thanks for finding that and the PR. We're currently [updating `libvirt` to the latest version](https://github.com/microsoft/CBL-Mariner/pull/1838) and the update should hopefully address that issue (among other things).

**Comment by aostapenko** [comment] 2022-01-04 20:45
Hey, yes I just saw your pull request - Thanks! Will check it out.

**Comment by christopherco** [comment] 2023-12-05 21:55
Looks to be fixed. Closing out the issue. Please open a new issue if the problem is still present.

**Closed by christopherco** 2023-12-05 21:55 UTC
