### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by raj07raj** [microsoft/CBL-Mariner#1214] opened 2021-07-30 15:59 UTC
Hi Team,

I got below error while building iso.

Downloading toolchain RPM: kernel-headers-5.10.52.1-1.cm1.noarch.rpm
	--2021-07-30 15:55:16--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/kernel-headers-5.10.52.1-1.cm1.noarch.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... 52.163.211.218
	Connecting to packages.microsoft.com (packages.microsoft.com)|52.163.211.218|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2021-07-30 15:55:17 ERROR 404: Not Found.

I also validated by looking into below path and package is not there. 
https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/

Regards,
Rajnish Soni

**Comment by thcrain-msft** [comment] 2021-07-30 19:59
Hi Rajnish, can you confirm which branch/tag you're building from? Currently, we can only guarantee that the package versions from the `1.0-stable` tag are retrievable from our repository on `packages.microsoft.com`.

**Comment by MateuszMalisz** [comment] 2021-07-30 23:01
Duplicate of #1191 . If the linked issue did not resolve your problem, feel free to reopen this with more information. Thank you!

**Closed by MateuszMalisz** 2021-07-30 23:01 UTC
